
PRODUCT_COPY_FILES += \
    vendor/umi/MAX/proprietary/bin/6620_launcher:system/bin/6620_launcher \
    vendor/umi/MAX/proprietary/bin/6620_wmt_concurrency:system/bin/6620_wmt_concurrency \
    vendor/umi/MAX/proprietary/bin/6620_wmt_lpbk:system/bin/6620_wmt_lpbk \
    vendor/umi/MAX/proprietary/bin/AcdApiDaemon:system/bin/AcdApiDaemon \
    vendor/umi/MAX/proprietary/bin/aee:system/bin/aee \
    vendor/umi/MAX/proprietary/bin/aee_archive:system/bin/aee_archive \
    vendor/umi/MAX/proprietary/bin/aee_core_forwarder:system/bin/aee_core_forwarder \
    vendor/umi/MAX/proprietary/bin/agoldnvram:system/bin/agoldnvram \
    vendor/umi/MAX/proprietary/bin/akmd09911:system/bin/akmd09911 \
    vendor/umi/MAX/proprietary/bin/akmd8963:system/bin/akmd8963 \
    vendor/umi/MAX/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/umi/MAX/proprietary/bin/ami304d:system/bin/ami304d \
    vendor/umi/MAX/proprietary/bin/atcid:system/bin/atcid \
    vendor/umi/MAX/proprietary/bin/atci_service:system/bin/atci_service \
    vendor/umi/MAX/proprietary/bin/audiocmdservice_atci:system/bin/audiocmdservice_atci \
    vendor/umi/MAX/proprietary/bin/autobt:system/bin/autobt \
    vendor/umi/MAX/proprietary/bin/autokd:system/bin/autokd \
    vendor/umi/MAX/proprietary/bin/batterywarning:system/bin/batterywarning \
    vendor/umi/MAX/proprietary/bin/bmm050d:system/bin/bmm050d \
    vendor/umi/MAX/proprietary/bin/boot_logo_updater:system/bin/boot_logo_updater \
    vendor/umi/MAX/proprietary/bin/ccci_fsd:system/bin/ccci_fsd \
    vendor/umi/MAX/proprietary/bin/ccci_mdinit:system/bin/ccci_mdinit \
    vendor/umi/MAX/proprietary/bin/dhcp6c:system/bin/dhcp6c \
    vendor/umi/MAX/proprietary/bin/dhcp6ctl:system/bin/dhcp6ctl \
    vendor/umi/MAX/proprietary/bin/dhcp6s:system/bin/dhcp6s \
    vendor/umi/MAX/proprietary/bin/dm_agent_binder:system/bin/dm_agent_binder \
    vendor/umi/MAX/proprietary/bin/dmlog:system/bin/dmlog \
    vendor/umi/MAX/proprietary/bin/emdlogger1:system/bin/emdlogger1 \
    vendor/umi/MAX/proprietary/bin/em_svr:system/bin/em_svr \
    vendor/umi/MAX/proprietary/bin/fingerprintd:system/bin/fingerprintd \
    vendor/umi/MAX/proprietary/bin/fsck_msdos_mtk:system/bin/fsck_msdos_mtk \
    vendor/umi/MAX/proprietary/bin/fuelgauged:system/bin/fuelgauged \
    vendor/umi/MAX/proprietary/bin/gas_srv:system/bin/gas_srv \
    vendor/umi/MAX/proprietary/bin/ged_srv:system/bin/ged_srv \
    vendor/umi/MAX/proprietary/bin/geomagneticd:system/bin/geomagneticd \
    vendor/umi/MAX/proprietary/bin/guiext-server:system/bin/guiext-server \
    vendor/umi/MAX/proprietary/bin/kpoc_charger:system/bin/kpoc_charger \
    vendor/umi/MAX/proprietary/bin/lsm303md:system/bin/lsm303md \
    vendor/umi/MAX/proprietary/bin/magd:system/bin/magd \
    vendor/umi/MAX/proprietary/bin/matv:system/bin/matv \
    vendor/umi/MAX/proprietary/bin/mc6420d:system/bin/mc6420d \
    vendor/umi/MAX/proprietary/bin/md_ctrl:system/bin/md_ctrl \
    vendor/umi/MAX/proprietary/bin/mdlogger:system/bin/mdlogger \
    vendor/umi/MAX/proprietary/bin/memsicd:system/bin/memsicd \
    vendor/umi/MAX/proprietary/bin/memsicd3416x:system/bin/memsicd3416x \
    vendor/umi/MAX/proprietary/bin/memsicd3524x:system/bin/memsicd3524x \
    vendor/umi/MAX/proprietary/bin/mfv_ut:system/bin/mfv_ut \
    vendor/umi/MAX/proprietary/bin/mobile_log_d:system/bin/mobile_log_d \
    vendor/umi/MAX/proprietary/bin/msensord:system/bin/msensord \
    vendor/umi/MAX/proprietary/bin/mtk_agpsd:system/bin/mtk_agpsd \
    vendor/umi/MAX/proprietary/bin/MtkCodecService:system/bin/MtkCodecService \
    vendor/umi/MAX/proprietary/bin/muxreport:system/bin/muxreport \
    vendor/umi/MAX/proprietary/bin/netdiag:system/bin/netdiag \
    vendor/umi/MAX/proprietary/bin/nvram_agent_binder:system/bin/nvram_agent_binder \
    vendor/umi/MAX/proprietary/bin/nvram_daemon:system/bin/nvram_daemon \
    vendor/umi/MAX/proprietary/bin/nvram_proximity:system/bin/nvram_proximity \
    vendor/umi/MAX/proprietary/bin/orientationd:system/bin/orientationd \
    vendor/umi/MAX/proprietary/bin/ppl_agent:system/bin/ppl_agent \
    vendor/umi/MAX/proprietary/bin/pppd_dt:system/bin/pppd_dt \
    vendor/umi/MAX/proprietary/bin/pq:system/bin/pq \
    vendor/umi/MAX/proprietary/bin/program_binary_service:system/bin/program_binary_service \
    vendor/umi/MAX/proprietary/bin/qmcX983d:system/bin/qmcX983d \
    vendor/umi/MAX/proprietary/bin/radvd:system/bin/radvd \
    vendor/umi/MAX/proprietary/bin/sn:system/bin/sn \
    vendor/umi/MAX/proprietary/bin/spm_loader:system/bin/spm_loader \
    vendor/umi/MAX/proprietary/bin/stp_dump3:system/bin/stp_dump3 \
    vendor/umi/MAX/proprietary/bin/terservice:system/bin/terservice \
    vendor/umi/MAX/proprietary/bin/vtservice:system/bin/vtservice \
    vendor/umi/MAX/proprietary/bin/wifi2agps:system/bin/wifi2agps \
    vendor/umi/MAX/proprietary/bin/wmt_loader:system/bin/wmt_loader \
    vendor/umi/MAX/proprietary/bin/xlog:system/bin/xlog \
    vendor/umi/MAX/proprietary/etc/custom.conf:system/etc/custom.conf \
    vendor/umi/MAX/proprietary/etc/firmware/catcher_filter_1_ulwctg_n.bin:system/etc/firmware/catcher_filter_1_ulwctg_n.bin \
    vendor/umi/MAX/proprietary/etc/firmware/dsp_1_ulwctg_n.bin:system/etc/firmware/dsp_1_ulwctg_n.bin \
    vendor/umi/MAX/proprietary/etc/firmware/modem_1_ulwctg_n.img:system/etc/firmware/modem_1_ulwctg_n.img \
    vendor/umi/MAX/proprietary/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v1_coeff.bin \
    vendor/umi/MAX/proprietary/etc/firmware/mt6627/mt6627_fm_v1_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v1_patch.bin \
    vendor/umi/MAX/proprietary/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v2_coeff.bin \
    vendor/umi/MAX/proprietary/etc/firmware/mt6627/mt6627_fm_v2_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v2_patch.bin \
    vendor/umi/MAX/proprietary/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v3_coeff.bin \
    vendor/umi/MAX/proprietary/etc/firmware/mt6627/mt6627_fm_v3_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v3_patch.bin \
    vendor/umi/MAX/proprietary/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v4_coeff.bin \
    vendor/umi/MAX/proprietary/etc/firmware/mt6627/mt6627_fm_v4_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v4_patch.bin \
    vendor/umi/MAX/proprietary/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin:system/etc/firmware/mt6627/mt6627_fm_v5_coeff.bin \
    vendor/umi/MAX/proprietary/etc/firmware/mt6627/mt6627_fm_v5_patch.bin:system/etc/firmware/mt6627/mt6627_fm_v5_patch.bin \
    vendor/umi/MAX/proprietary/etc/firmware/pcm_deepidle.bin:system/etc/firmware/pcm_deepidle.bin \
    vendor/umi/MAX/proprietary/etc/firmware/pcm_deepidle_by_mp1.bin:system/etc/firmware/pcm_deepidle_by_mp1.bin \
    vendor/umi/MAX/proprietary/etc/firmware/pcm_mcdi_ddrdfs.bin:system/etc/firmware/pcm_mcdi_ddrdfs.bin \
    vendor/umi/MAX/proprietary/etc/firmware/pcm_sodi_ddrdfs.bin:system/etc/firmware/pcm_sodi_ddrdfs.bin \
    vendor/umi/MAX/proprietary/etc/firmware/pcm_sodi_ddrdfs_by_mp1.bin:system/etc/firmware/pcm_sodi_ddrdfs_by_mp1.bin \
    vendor/umi/MAX/proprietary/etc/firmware/pcm_suspend.bin:system/etc/firmware/pcm_suspend.bin \
    vendor/umi/MAX/proprietary/etc/firmware/pcm_suspend_by_mp1.bin:system/etc/firmware/pcm_suspend_by_mp1.bin \
    vendor/umi/MAX/proprietary/etc/firmware/ROMv2_lm_patch_1_0_hdr.bin:system/etc/firmware/ROMv2_lm_patch_1_0_hdr.bin \
    vendor/umi/MAX/proprietary/etc/firmware/ROMv2_lm_patch_1_1_hdr.bin:system/etc/firmware/ROMv2_lm_patch_1_1_hdr.bin \
    vendor/umi/MAX/proprietary/etc/firmware/WIFI_RAM_CODE_6755:system/etc/firmware/WIFI_RAM_CODE_6755 \
    vendor/umi/MAX/proprietary/etc/firmware/WMT_SOC.cfg:system/etc/firmware/WMT_SOC.cfg \
    vendor/umi/MAX/proprietary/etc/mtklog-config.prop:system/etc/mtklog-config.prop \
    vendor/umi/MAX/proprietary/etc/radvd/radvd.conf:system/etc/radvd/radvd.conf \
    vendor/umi/MAX/proprietary/lib/egl/libGLES_mali.so:system/lib/egl/libGLES_mali.so \
    vendor/umi/MAX/proprietary/lib64/egl/libGLES_mali.so:system/lib64/egl/libGLES_mali.so \
    vendor/umi/MAX/proprietary/lib/hw/audio.primary.mt6755.so:system/lib/hw/audio.primary.mt6755.so \
    vendor/umi/MAX/proprietary/lib64/hw/audio.primary.mt6755.so:system/lib64/hw/audio.primary.mt6755.so \
    vendor/umi/MAX/proprietary/lib/hw/camera.mt6755.so:system/lib/hw/camera.mt6755.so \
    vendor/umi/MAX/proprietary/lib64/hw/camera.mt6755.so:system/lib64/hw/camera.mt6755.so \
    vendor/umi/MAX/proprietary/lib64/hw/fingerprint_madev.default.so:system/lib64/hw/fingerprint_madev.default.so \
    vendor/umi/MAX/proprietary/lib64/hw/fingerprint_sunwave.default.so:system/lib64/hw/fingerprint_sunwave.default.so \
    vendor/umi/MAX/proprietary/lib/hw/gps.mt6755.so:system/lib/hw/gps.mt6755.so \
    vendor/umi/MAX/proprietary/lib64/hw/gps.mt6755.so:system/lib64/hw/gps.mt6755.so \
    vendor/umi/MAX/proprietary/lib/hw/gralloc.mt6755.so:system/lib/hw/gralloc.mt6755.so \
    vendor/umi/MAX/proprietary/lib64/hw/gralloc.mt6755.so:system/lib64/hw/gralloc.mt6755.so \
    vendor/umi/MAX/proprietary/lib/hw/hwcomposer.mt6755.so:system/lib/hw/hwcomposer.mt6755.so \
    vendor/umi/MAX/proprietary/lib64/hw/hwcomposer.mt6755.so:system/lib64/hw/hwcomposer.mt6755.so \
    vendor/umi/MAX/proprietary/lib/hw/memtrack.mt6755.so:system/lib/hw/memtrack.mt6755.so \
    vendor/umi/MAX/proprietary/lib64/hw/memtrack.mt6755.so:system/lib64/hw/memtrack.mt6755.so \
    vendor/umi/MAX/proprietary/lib/hw/mmsdk.mt6755.so:system/lib/hw/mmsdk.mt6755.so \
    vendor/umi/MAX/proprietary/lib64/hw/mmsdk.mt6755.so:system/lib64/hw/mmsdk.mt6755.so \
    vendor/umi/MAX/proprietary/lib/hw/sensors.mt6755.so:system/lib/hw/sensors.mt6755.so \
    vendor/umi/MAX/proprietary/lib64/hw/sensors.mt6755.so:system/lib64/hw/sensors.mt6755.so \
    vendor/umi/MAX/proprietary/lib/lib3a_sample.so:system/lib/lib3a_sample.so \
    vendor/umi/MAX/proprietary/lib64/lib3a_sample.so:system/lib64/lib3a_sample.so \
    vendor/umi/MAX/proprietary/lib/lib3a.so:system/lib/lib3a.so \
    vendor/umi/MAX/proprietary/lib64/lib3a.so:system/lib64/lib3a.so \
    vendor/umi/MAX/proprietary/lib/liba3m.so:system/lib/liba3m.so \
    vendor/umi/MAX/proprietary/lib64/liba3m.so:system/lib64/liba3m.so \
    vendor/umi/MAX/proprietary/lib/libacdk.so:system/lib/libacdk.so \
    vendor/umi/MAX/proprietary/lib64/libacdk.so:system/lib64/libacdk.so \
    vendor/umi/MAX/proprietary/lib/libaed.so:system/lib/libaed.so \
    vendor/umi/MAX/proprietary/lib64/libaed.so:system/lib64/libaed.so \
    vendor/umi/MAX/proprietary/lib/lib_agoldcam_s5k3l8_mipi_raw_SY_50013A1_v1.so:system/lib/lib_agoldcam_s5k3l8_mipi_raw_SY_50013A1_v1.so \
    vendor/umi/MAX/proprietary/lib64/lib_agoldcam_s5k3l8_mipi_raw_SY_50013A1_v1.so:system/lib64/lib_agoldcam_s5k3l8_mipi_raw_SY_50013A1_v1.so \
    vendor/umi/MAX/proprietary/lib/lib_agoldcam_s5k3l8_mipi_raw_SY_U5BM13_v1.so:system/lib/lib_agoldcam_s5k3l8_mipi_raw_SY_U5BM13_v1.so \
    vendor/umi/MAX/proprietary/lib64/lib_agoldcam_s5k3l8_mipi_raw_SY_U5BM13_v1.so:system/lib64/lib_agoldcam_s5k3l8_mipi_raw_SY_U5BM13_v1.so \
    vendor/umi/MAX/proprietary/lib/lib_agoldlens_dw9714af_v1.so:system/lib/lib_agoldlens_dw9714af_v1.so \
    vendor/umi/MAX/proprietary/lib64/lib_agoldlens_dw9714af_v1.so:system/lib64/lib_agoldlens_dw9714af_v1.so \
    vendor/umi/MAX/proprietary/lib/lib_agoldlens_dw9714af_v2.so:system/lib/lib_agoldlens_dw9714af_v2.so \
    vendor/umi/MAX/proprietary/lib64/lib_agoldlens_dw9714af_v2.so:system/lib64/lib_agoldlens_dw9714af_v2.so \
    vendor/umi/MAX/proprietary/lib/lib_agoldlens_dw9714af_v3.so:system/lib/lib_agoldlens_dw9714af_v3.so \
    vendor/umi/MAX/proprietary/lib64/lib_agoldlens_dw9714af_v3.so:system/lib64/lib_agoldlens_dw9714af_v3.so \
    vendor/umi/MAX/proprietary/lib/lib_agoldlens_dw9714af_v4.so:system/lib/lib_agoldlens_dw9714af_v4.so \
    vendor/umi/MAX/proprietary/lib64/lib_agoldlens_dw9714af_v4.so:system/lib64/lib_agoldlens_dw9714af_v4.so \
    vendor/umi/MAX/proprietary/lib/lib_agoldlens_dw9763af_v1.so:system/lib/lib_agoldlens_dw9763af_v1.so \
    vendor/umi/MAX/proprietary/lib64/lib_agoldlens_dw9763af_v1.so:system/lib64/lib_agoldlens_dw9763af_v1.so \
    vendor/umi/MAX/proprietary/lib/lib_agoldlens_dw9763af_v2.so:system/lib/lib_agoldlens_dw9763af_v2.so \
    vendor/umi/MAX/proprietary/lib64/lib_agoldlens_dw9763af_v2.so:system/lib64/lib_agoldlens_dw9763af_v2.so \
    vendor/umi/MAX/proprietary/lib/lib_agoldlens_dw9800af_v1.so:system/lib/lib_agoldlens_dw9800af_v1.so \
    vendor/umi/MAX/proprietary/lib64/lib_agoldlens_dw9800af_v1.so:system/lib64/lib_agoldlens_dw9800af_v1.so \
    vendor/umi/MAX/proprietary/lib/lib_agoldlens_dw9800af_v2.so:system/lib/lib_agoldlens_dw9800af_v2.so \
    vendor/umi/MAX/proprietary/lib64/lib_agoldlens_dw9800af_v2.so:system/lib64/lib_agoldlens_dw9800af_v2.so \
    vendor/umi/MAX/proprietary/lib/lib_agoldlens_dw9800af_v3.so:system/lib/lib_agoldlens_dw9800af_v3.so \
    vendor/umi/MAX/proprietary/lib64/lib_agoldlens_dw9800af_v3.so:system/lib64/lib_agoldlens_dw9800af_v3.so \
    vendor/umi/MAX/proprietary/lib/libagoldtpglove_jni.so:system/lib/libagoldtpglove_jni.so \
    vendor/umi/MAX/proprietary/lib64/libagoldtpglove_jni.so:system/lib64/libagoldtpglove_jni.so \
    vendor/umi/MAX/proprietary/lib/libatciserv_jni.so:system/lib/libatciserv_jni.so \
    vendor/umi/MAX/proprietary/lib64/libatciserv_jni.so:system/lib64/libatciserv_jni.so \
    vendor/umi/MAX/proprietary/lib/libatvctrlservice.so:system/lib/libatvctrlservice.so \
    vendor/umi/MAX/proprietary/lib64/libatvctrlservice.so:system/lib64/libatvctrlservice.so \
    vendor/umi/MAX/proprietary/lib/libaudiocompensationfilter.so:system/lib/libaudiocompensationfilter.so \
    vendor/umi/MAX/proprietary/lib64/libaudiocompensationfilter.so:system/lib64/libaudiocompensationfilter.so \
    vendor/umi/MAX/proprietary/lib/libaudiocomponentengine.so:system/lib/libaudiocomponentengine.so \
    vendor/umi/MAX/proprietary/lib64/libaudiocomponentengine.so:system/lib64/libaudiocomponentengine.so \
    vendor/umi/MAX/proprietary/lib/libaudiocustparam.so:system/lib/libaudiocustparam.so \
    vendor/umi/MAX/proprietary/lib64/libaudiocustparam.so:system/lib64/libaudiocustparam.so \
    vendor/umi/MAX/proprietary/lib/libaudiodcrflt.so:system/lib/libaudiodcrflt.so \
    vendor/umi/MAX/proprietary/lib64/libaudiodcrflt.so:system/lib64/libaudiodcrflt.so \
    vendor/umi/MAX/proprietary/lib/libaudiomtkdcremoval.so:system/lib/libaudiomtkdcremoval.so \
    vendor/umi/MAX/proprietary/lib/libaudio_param_parser.so:system/lib/libaudio_param_parser.so \
    vendor/umi/MAX/proprietary/lib64/libaudio_param_parser.so:system/lib64/libaudio_param_parser.so \
    vendor/umi/MAX/proprietary/lib/libaudiosetting.so:system/lib/libaudiosetting.so \
    vendor/umi/MAX/proprietary/lib64/libaudiosetting.so:system/lib64/libaudiosetting.so \
    vendor/umi/MAX/proprietary/lib/libbessound_hd_mtk.so:system/lib/libbessound_hd_mtk.so \
    vendor/umi/MAX/proprietary/lib64/libbessound_hd_mtk.so:system/lib64/libbessound_hd_mtk.so \
    vendor/umi/MAX/proprietary/lib/libbessurround_mtk.so:system/lib/libbessurround_mtk.so \
    vendor/umi/MAX/proprietary/lib/libblisrc32.so:system/lib/libblisrc32.so \
    vendor/umi/MAX/proprietary/lib64/libblisrc32.so:system/lib64/libblisrc32.so \
    vendor/umi/MAX/proprietary/lib/libblisrc.so:system/lib/libblisrc.so \
    vendor/umi/MAX/proprietary/lib64/libblisrc.so:system/lib64/libblisrc.so \
    vendor/umi/MAX/proprietary/lib/libbluetoothem_mtk.so:system/lib/libbluetoothem_mtk.so \
    vendor/umi/MAX/proprietary/lib64/libbluetoothem_mtk.so:system/lib64/libbluetoothem_mtk.so \
    vendor/umi/MAX/proprietary/lib/libbluetooth_mtk_pure.so:system/lib/libbluetooth_mtk_pure.so \
    vendor/umi/MAX/proprietary/lib64/libbluetooth_mtk_pure.so:system/lib64/libbluetooth_mtk_pure.so \
    vendor/umi/MAX/proprietary/lib/libbluetooth_mtk.so:system/lib/libbluetooth_mtk.so \
    vendor/umi/MAX/proprietary/lib64/libbluetooth_mtk.so:system/lib64/libbluetooth_mtk.so \
    vendor/umi/MAX/proprietary/lib/libbluetooth_relayer.so:system/lib/libbluetooth_relayer.so \
    vendor/umi/MAX/proprietary/lib64/libbluetooth_relayer.so:system/lib64/libbluetooth_relayer.so \
    vendor/umi/MAX/proprietary/lib/libBnMtkCodec.so:system/lib/libBnMtkCodec.so \
    vendor/umi/MAX/proprietary/lib64/libBnMtkCodec.so:system/lib64/libBnMtkCodec.so \
    vendor/umi/MAX/proprietary/lib/libbwc.so:system/lib/libbwc.so \
    vendor/umi/MAX/proprietary/lib64/libbwc.so:system/lib64/libbwc.so \
    vendor/umi/MAX/proprietary/lib/libcam1_utils.so:system/lib/libcam1_utils.so \
    vendor/umi/MAX/proprietary/lib64/libcam1_utils.so:system/lib64/libcam1_utils.so \
    vendor/umi/MAX/proprietary/lib/libcam3_app.so:system/lib/libcam3_app.so \
    vendor/umi/MAX/proprietary/lib64/libcam3_app.so:system/lib64/libcam3_app.so \
    vendor/umi/MAX/proprietary/lib/libcam3_hwnode.so:system/lib/libcam3_hwnode.so \
    vendor/umi/MAX/proprietary/lib64/libcam3_hwnode.so:system/lib64/libcam3_hwnode.so \
    vendor/umi/MAX/proprietary/lib/libcam3_hwpipeline.so:system/lib/libcam3_hwpipeline.so \
    vendor/umi/MAX/proprietary/lib64/libcam3_hwpipeline.so:system/lib64/libcam3_hwpipeline.so \
    vendor/umi/MAX/proprietary/lib/libcam3_pipeline.so:system/lib/libcam3_pipeline.so \
    vendor/umi/MAX/proprietary/lib64/libcam3_pipeline.so:system/lib64/libcam3_pipeline.so \
    vendor/umi/MAX/proprietary/lib/libcam3_utils.so:system/lib/libcam3_utils.so \
    vendor/umi/MAX/proprietary/lib64/libcam3_utils.so:system/lib64/libcam3_utils.so \
    vendor/umi/MAX/proprietary/lib/libcamalgo.so:system/lib/libcamalgo.so \
    vendor/umi/MAX/proprietary/lib64/libcamalgo.so:system/lib64/libcamalgo.so \
    vendor/umi/MAX/proprietary/lib/libcam.camadapter.so:system/lib/libcam.camadapter.so \
    vendor/umi/MAX/proprietary/lib64/libcam.camadapter.so:system/lib64/libcam.camadapter.so \
    vendor/umi/MAX/proprietary/lib/libcam.camnode.so:system/lib/libcam.camnode.so \
    vendor/umi/MAX/proprietary/lib64/libcam.camnode.so:system/lib64/libcam.camnode.so \
    vendor/umi/MAX/proprietary/lib/libcam.camshot.so:system/lib/libcam.camshot.so \
    vendor/umi/MAX/proprietary/lib64/libcam.camshot.so:system/lib64/libcam.camshot.so \
    vendor/umi/MAX/proprietary/lib/libcam.client.so:system/lib/libcam.client.so \
    vendor/umi/MAX/proprietary/lib64/libcam.client.so:system/lib64/libcam.client.so \
    vendor/umi/MAX/proprietary/lib/libcam.device1.so:system/lib/libcam.device1.so \
    vendor/umi/MAX/proprietary/lib64/libcam.device1.so:system/lib64/libcam.device1.so \
    vendor/umi/MAX/proprietary/lib/libcam.device3.so:system/lib/libcam.device3.so \
    vendor/umi/MAX/proprietary/lib64/libcam.device3.so:system/lib64/libcam.device3.so \
    vendor/umi/MAX/proprietary/lib/libcamdrv.so:system/lib/libcamdrv.so \
    vendor/umi/MAX/proprietary/lib64/libcamdrv.so:system/lib64/libcamdrv.so \
    vendor/umi/MAX/proprietary/lib/libcameracustom.so:system/lib/libcameracustom.so \
    vendor/umi/MAX/proprietary/lib64/libcameracustom.so:system/lib64/libcameracustom.so \
    vendor/umi/MAX/proprietary/lib/libcam.exif.so:system/lib/libcam.exif.so \
    vendor/umi/MAX/proprietary/lib64/libcam.exif.so:system/lib64/libcam.exif.so \
    vendor/umi/MAX/proprietary/lib/libcam.exif.v3.so:system/lib/libcam.exif.v3.so \
    vendor/umi/MAX/proprietary/lib64/libcam.exif.v3.so:system/lib64/libcam.exif.v3.so \
    vendor/umi/MAX/proprietary/lib/libcam.hal3a.v3.dng.so:system/lib/libcam.hal3a.v3.dng.so \
    vendor/umi/MAX/proprietary/lib64/libcam.hal3a.v3.dng.so:system/lib64/libcam.hal3a.v3.dng.so \
    vendor/umi/MAX/proprietary/lib/libcam.hal3a.v3.so:system/lib/libcam.hal3a.v3.so \
    vendor/umi/MAX/proprietary/lib64/libcam.hal3a.v3.so:system/lib64/libcam.hal3a.v3.so \
    vendor/umi/MAX/proprietary/lib/libcam.halsensor.so:system/lib/libcam.halsensor.so \
    vendor/umi/MAX/proprietary/lib64/libcam.halsensor.so:system/lib64/libcam.halsensor.so \
    vendor/umi/MAX/proprietary/lib/libcam_hwutils.so:system/lib/libcam_hwutils.so \
    vendor/umi/MAX/proprietary/lib64/libcam_hwutils.so:system/lib64/libcam_hwutils.so \
    vendor/umi/MAX/proprietary/lib/libcam.iopipe.so:system/lib/libcam.iopipe.so \
    vendor/umi/MAX/proprietary/lib/libcam.metadataprovider.so:system/lib/libcam.metadataprovider.so \
    vendor/umi/MAX/proprietary/lib64/libcam.metadataprovider.so:system/lib64/libcam.metadataprovider.so \
    vendor/umi/MAX/proprietary/lib/libcam.metadata.so:system/lib/libcam.metadata.so \
    vendor/umi/MAX/proprietary/lib64/libcam.metadata.so:system/lib64/libcam.metadata.so \
    vendor/umi/MAX/proprietary/lib/libcam_mmp.so:system/lib/libcam_mmp.so \
    vendor/umi/MAX/proprietary/lib64/libcam_mmp.so:system/lib64/libcam_mmp.so \
    vendor/umi/MAX/proprietary/lib/libcam.paramsmgr.so:system/lib/libcam.paramsmgr.so \
    vendor/umi/MAX/proprietary/lib64/libcam.paramsmgr.so:system/lib64/libcam.paramsmgr.so \
    vendor/umi/MAX/proprietary/lib/libcam_platform.so:system/lib/libcam_platform.so \
    vendor/umi/MAX/proprietary/lib64/libcam_platform.so:system/lib64/libcam_platform.so \
    vendor/umi/MAX/proprietary/lib/libcam.sdkclient.so:system/lib/libcam.sdkclient.so \
    vendor/umi/MAX/proprietary/lib64/libcam.sdkclient.so:system/lib64/libcam.sdkclient.so \
    vendor/umi/MAX/proprietary/lib/libcam.utils.cpuctrl.so:system/lib/libcam.utils.cpuctrl.so \
    vendor/umi/MAX/proprietary/lib64/libcam.utils.cpuctrl.so:system/lib64/libcam.utils.cpuctrl.so \
    vendor/umi/MAX/proprietary/lib/libcam.utils.sensorlistener.so:system/lib/libcam.utils.sensorlistener.so \
    vendor/umi/MAX/proprietary/lib64/libcam.utils.sensorlistener.so:system/lib64/libcam.utils.sensorlistener.so \
    vendor/umi/MAX/proprietary/lib/libcam_utils.so:system/lib/libcam_utils.so \
    vendor/umi/MAX/proprietary/lib64/libcam_utils.so:system/lib64/libcam_utils.so \
    vendor/umi/MAX/proprietary/lib/libccci_util.so:system/lib/libccci_util.so \
    vendor/umi/MAX/proprietary/lib64/libccci_util.so:system/lib64/libccci_util.so \
    vendor/umi/MAX/proprietary/lib/libcustom_jni.so:system/lib/libcustom_jni.so \
    vendor/umi/MAX/proprietary/lib64/libcustom_jni.so:system/lib64/libcustom_jni.so \
    vendor/umi/MAX/proprietary/lib/libcustom_nvram.so:system/lib/libcustom_nvram.so \
    vendor/umi/MAX/proprietary/lib64/libcustom_nvram.so:system/lib64/libcustom_nvram.so \
    vendor/umi/MAX/proprietary/lib/libcustom_prop.so:system/lib/libcustom_prop.so \
    vendor/umi/MAX/proprietary/lib64/libcustom_prop.so:system/lib64/libcustom_prop.so \
    vendor/umi/MAX/proprietary/lib/libcvsd_mtk.so:system/lib/libcvsd_mtk.so \
    vendor/umi/MAX/proprietary/lib64/libcvsd_mtk.so:system/lib64/libcvsd_mtk.so \
    vendor/umi/MAX/proprietary/lib/libdcfdecoderjni.so:system/lib/libdcfdecoderjni.so \
    vendor/umi/MAX/proprietary/lib64/libdcfdecoderjni.so:system/lib64/libdcfdecoderjni.so \
    vendor/umi/MAX/proprietary/lib/libdirect-coredump.so:system/lib/libdirect-coredump.so \
    vendor/umi/MAX/proprietary/lib64/libdirect-coredump.so:system/lib64/libdirect-coredump.so \
    vendor/umi/MAX/proprietary/lib/libdngop.so:system/lib/libdngop.so \
    vendor/umi/MAX/proprietary/lib64/libdngop.so:system/lib64/libdngop.so \
    vendor/umi/MAX/proprietary/lib/libdpframework.so:system/lib/libdpframework.so \
    vendor/umi/MAX/proprietary/lib64/libdpframework.so:system/lib64/libdpframework.so \
    vendor/umi/MAX/proprietary/lib/libdrmmtkutil.so:system/lib/libdrmmtkutil.so \
    vendor/umi/MAX/proprietary/lib64/libdrmmtkutil.so:system/lib64/libdrmmtkutil.so \
    vendor/umi/MAX/proprietary/lib/libdrmmtkwhitelist.so:system/lib/libdrmmtkwhitelist.so \
    vendor/umi/MAX/proprietary/lib64/libdrmmtkwhitelist.so:system/lib64/libdrmmtkwhitelist.so \
    vendor/umi/MAX/proprietary/lib/libeffect.facebeautypp.so:system/lib/libeffect.facebeautypp.so \
    vendor/umi/MAX/proprietary/lib64/libeffect.facebeautypp.so:system/lib64/libeffect.facebeautypp.so \
    vendor/umi/MAX/proprietary/lib/libeffecthal.base.so:system/lib/libeffecthal.base.so \
    vendor/umi/MAX/proprietary/lib64/libeffecthal.base.so:system/lib64/libeffecthal.base.so \
    vendor/umi/MAX/proprietary/lib/libeffecthal.JPG.so:system/lib/libeffecthal.JPG.so \
    vendor/umi/MAX/proprietary/lib64/libeffecthal.JPG.so:system/lib64/libeffecthal.JPG.so \
    vendor/umi/MAX/proprietary/lib/libem_bt_jni.so:system/lib/libem_bt_jni.so \
    vendor/umi/MAX/proprietary/lib64/libem_bt_jni.so:system/lib64/libem_bt_jni.so \
    vendor/umi/MAX/proprietary/lib/libem_gpio_jni.so:system/lib/libem_gpio_jni.so \
    vendor/umi/MAX/proprietary/lib64/libem_gpio_jni.so:system/lib64/libem_gpio_jni.so \
    vendor/umi/MAX/proprietary/lib/libem_lte_jni.so:system/lib/libem_lte_jni.so \
    vendor/umi/MAX/proprietary/lib64/libem_lte_jni.so:system/lib64/libem_lte_jni.so \
    vendor/umi/MAX/proprietary/lib/libem_modem_jni.so:system/lib/libem_modem_jni.so \
    vendor/umi/MAX/proprietary/lib64/libem_modem_jni.so:system/lib64/libem_modem_jni.so \
    vendor/umi/MAX/proprietary/lib/libem_sensor_jni.so:system/lib/libem_sensor_jni.so \
    vendor/umi/MAX/proprietary/lib64/libem_sensor_jni.so:system/lib64/libem_sensor_jni.so \
    vendor/umi/MAX/proprietary/lib/libem_support_jni.so:system/lib/libem_support_jni.so \
    vendor/umi/MAX/proprietary/lib64/libem_support_jni.so:system/lib64/libem_support_jni.so \
    vendor/umi/MAX/proprietary/lib/libem_usb_jni.so:system/lib/libem_usb_jni.so \
    vendor/umi/MAX/proprietary/lib64/libem_usb_jni.so:system/lib64/libem_usb_jni.so \
    vendor/umi/MAX/proprietary/lib/libem_wifi_jni.so:system/lib/libem_wifi_jni.so \
    vendor/umi/MAX/proprietary/lib64/libem_wifi_jni.so:system/lib64/libem_wifi_jni.so \
    vendor/umi/MAX/proprietary/lib/libfeatureiodrv.so:system/lib/libfeatureiodrv.so \
    vendor/umi/MAX/proprietary/lib/libfeatureio.so:system/lib/libfeatureio.so \
    vendor/umi/MAX/proprietary/lib/libfile_op.so:system/lib/libfile_op.so \
    vendor/umi/MAX/proprietary/lib/libgas.so:system/lib/libgas.so \
    vendor/umi/MAX/proprietary/lib64/libgas.so:system/lib64/libgas.so \
    vendor/umi/MAX/proprietary/lib/libged.so:system/lib/libged.so \
    vendor/umi/MAX/proprietary/lib64/libged.so:system/lib64/libged.so \
    vendor/umi/MAX/proprietary/lib/libgem.so:system/lib/libgem.so \
    vendor/umi/MAX/proprietary/lib64/libgem.so:system/lib64/libgem.so \
    vendor/umi/MAX/proprietary/lib/libgpu_aux.so:system/lib/libgpu_aux.so \
    vendor/umi/MAX/proprietary/lib64/libgpu_aux.so:system/lib64/libgpu_aux.so \
    vendor/umi/MAX/proprietary/lib/libgralloc_extra.so:system/lib/libgralloc_extra.so \
    vendor/umi/MAX/proprietary/lib64/libgralloc_extra.so:system/lib64/libgralloc_extra.so \
    vendor/umi/MAX/proprietary/lib/libhdrproc.so:system/lib/libhdrproc.so \
    vendor/umi/MAX/proprietary/lib64/libhdrproc.so:system/lib64/libhdrproc.so \
    vendor/umi/MAX/proprietary/lib/libhwm.so:system/lib/libhwm.so \
    vendor/umi/MAX/proprietary/lib64/libhwm.so:system/lib64/libhwm.so \
    vendor/umi/MAX/proprietary/lib/libimageio_plat_drv.so:system/lib/libimageio_plat_drv.so \
    vendor/umi/MAX/proprietary/lib64/libimageio_plat_drv.so:system/lib64/libimageio_plat_drv.so \
    vendor/umi/MAX/proprietary/lib/libimageio.so:system/lib/libimageio.so \
    vendor/umi/MAX/proprietary/lib64/libimageio.so:system/lib64/libimageio.so \
    vendor/umi/MAX/proprietary/lib/libion_mtk.so:system/lib/libion_mtk.so \
    vendor/umi/MAX/proprietary/lib64/libion_mtk.so:system/lib64/libion_mtk.so \
    vendor/umi/MAX/proprietary/lib/libion.so:system/lib/libion.so \
    vendor/umi/MAX/proprietary/lib64/libion.so:system/lib64/libion.so \
    vendor/umi/MAX/proprietary/lib/libja3m.so:system/lib/libja3m.so \
    vendor/umi/MAX/proprietary/lib64/libja3m.so:system/lib64/libja3m.so \
    vendor/umi/MAX/proprietary/lib/libjni_pq.so:system/lib/libjni_pq.so \
    vendor/umi/MAX/proprietary/lib64/libjni_pq.so:system/lib64/libjni_pq.so \
    vendor/umi/MAX/proprietary/lib/libJpgDecPipe.so:system/lib/libJpgDecPipe.so \
    vendor/umi/MAX/proprietary/lib64/libJpgDecPipe.so:system/lib64/libJpgDecPipe.so \
    vendor/umi/MAX/proprietary/lib/libJpgEncPipe.so:system/lib/libJpgEncPipe.so \
    vendor/umi/MAX/proprietary/lib64/libJpgEncPipe.so:system/lib64/libJpgEncPipe.so \
    vendor/umi/MAX/proprietary/lib/libm4u.so:system/lib/libm4u.so \
    vendor/umi/MAX/proprietary/lib64/libm4u.so:system/lib64/libm4u.so \
    vendor/umi/MAX/proprietary/lib/libmatv_cust.so:system/lib/libmatv_cust.so \
    vendor/umi/MAX/proprietary/lib64/libmatv_cust.so:system/lib64/libmatv_cust.so \
    vendor/umi/MAX/proprietary/lib/libmdloggerrecycle.so:system/lib/libmdloggerrecycle.so \
    vendor/umi/MAX/proprietary/lib64/libmdloggerrecycle.so:system/lib64/libmdloggerrecycle.so \
    vendor/umi/MAX/proprietary/lib/libmediatek_exceptionlog.so:system/lib/libmediatek_exceptionlog.so \
    vendor/umi/MAX/proprietary/lib64/libmediatek_exceptionlog.so:system/lib64/libmediatek_exceptionlog.so \
    vendor/umi/MAX/proprietary/lib64/libmemoryDumpEncoder.so:system/lib64/libmemoryDumpEncoder.so \
    vendor/umi/MAX/proprietary/lib/libmemorydumper.so:system/lib/libmemorydumper.so \
    vendor/umi/MAX/proprietary/lib64/libmemorydumper.so:system/lib64/libmemorydumper.so \
    vendor/umi/MAX/proprietary/lib/libmhalImageCodec.so:system/lib/libmhalImageCodec.so \
    vendor/umi/MAX/proprietary/lib64/libmhalImageCodec.so:system/lib64/libmhalImageCodec.so \
    vendor/umi/MAX/proprietary/lib/libmmprofile_jni.so:system/lib/libmmprofile_jni.so \
    vendor/umi/MAX/proprietary/lib64/libmmprofile_jni.so:system/lib64/libmmprofile_jni.so \
    vendor/umi/MAX/proprietary/lib/libmmprofile.so:system/lib/libmmprofile.so \
    vendor/umi/MAX/proprietary/lib64/libmmprofile.so:system/lib64/libmmprofile.so \
    vendor/umi/MAX/proprietary/lib/libmmsdkservice.so:system/lib/libmmsdkservice.so \
    vendor/umi/MAX/proprietary/lib64/libmmsdkservice.so:system/lib64/libmmsdkservice.so \
    vendor/umi/MAX/proprietary/lib/libmrdump.so:system/lib/libmrdump.so \
    vendor/umi/MAX/proprietary/lib64/libmrdump.so:system/lib64/libmrdump.so \
    vendor/umi/MAX/proprietary/lib/libmsbc_mtk.so:system/lib/libmsbc_mtk.so \
    vendor/umi/MAX/proprietary/lib64/libmsbc_mtk.so:system/lib64/libmsbc_mtk.so \
    vendor/umi/MAX/proprietary/lib/libmtkcamera_client.so:system/lib/libmtkcamera_client.so \
    vendor/umi/MAX/proprietary/lib64/libmtkcamera_client.so:system/lib64/libmtkcamera_client.so \
    vendor/umi/MAX/proprietary/lib/libmtk_drvb.so:system/lib/libmtk_drvb.so \
    vendor/umi/MAX/proprietary/lib64/libmtk_drvb.so:system/lib64/libmtk_drvb.so \
    vendor/umi/MAX/proprietary/lib/libmtkjpeg.so:system/lib/libmtkjpeg.so \
    vendor/umi/MAX/proprietary/lib64/libmtkjpeg.so:system/lib64/libmtkjpeg.so \
    vendor/umi/MAX/proprietary/lib/libmtklimiter.so:system/lib/libmtklimiter.so \
    vendor/umi/MAX/proprietary/lib64/libmtklimiter.so:system/lib64/libmtklimiter.so \
    vendor/umi/MAX/proprietary/lib/libmtk_mmutils.so:system/lib/libmtk_mmutils.so \
    vendor/umi/MAX/proprietary/lib64/libmtk_mmutils.so:system/lib64/libmtk_mmutils.so \
    vendor/umi/MAX/proprietary/lib/libMtkOmxCore.so:system/lib/libMtkOmxCore.so \
    vendor/umi/MAX/proprietary/lib64/libMtkOmxCore.so:system/lib64/libMtkOmxCore.so \
    vendor/umi/MAX/proprietary/lib/libmtkshifter.so:system/lib/libmtkshifter.so \
    vendor/umi/MAX/proprietary/lib64/libmtkshifter.so:system/lib64/libmtkshifter.so \
    vendor/umi/MAX/proprietary/lib/libMtkVideoTranscoder.so:system/lib/libMtkVideoTranscoder.so \
    vendor/umi/MAX/proprietary/lib64/libMtkVideoTranscoder.so:system/lib64/libMtkVideoTranscoder.so \
    vendor/umi/MAX/proprietary/lib/libn3d3a.so:system/lib/libn3d3a.so \
    vendor/umi/MAX/proprietary/lib64/libn3d3a.so:system/lib64/libn3d3a.so \
    vendor/umi/MAX/proprietary/lib/libnativecheck-jni.so:system/lib/libnativecheck-jni.so \
    vendor/umi/MAX/proprietary/lib64/libnativecheck-jni.so:system/lib64/libnativecheck-jni.so \
    vendor/umi/MAX/proprietary/lib/libnetutils.so:system/lib/libnetutils.so \
    vendor/umi/MAX/proprietary/lib64/libnetutils.so:system/lib64/libnetutils.so \
    vendor/umi/MAX/proprietary/lib/libnvramagentclient.so:system/lib/libnvramagentclient.so \
    vendor/umi/MAX/proprietary/lib64/libnvramagentclient.so:system/lib64/libnvramagentclient.so \
    vendor/umi/MAX/proprietary/lib/libnvram_daemon_callback.so:system/lib/libnvram_daemon_callback.so \
    vendor/umi/MAX/proprietary/lib64/libnvram_daemon_callback.so:system/lib64/libnvram_daemon_callback.so \
    vendor/umi/MAX/proprietary/lib/libnvram_platform.so:system/lib/libnvram_platform.so \
    vendor/umi/MAX/proprietary/lib64/libnvram_platform.so:system/lib64/libnvram_platform.so \
    vendor/umi/MAX/proprietary/lib/libnvram_sec.so:system/lib/libnvram_sec.so \
    vendor/umi/MAX/proprietary/lib64/libnvram_sec.so:system/lib64/libnvram_sec.so \
    vendor/umi/MAX/proprietary/lib/libnvram.so:system/lib/libnvram.so \
    vendor/umi/MAX/proprietary/lib64/libnvram.so:system/lib64/libnvram.so \
    vendor/umi/MAX/proprietary/lib/libperfservicenative.so:system/lib/libperfservicenative.so \
    vendor/umi/MAX/proprietary/lib64/libperfservicenative.so:system/lib64/libperfservicenative.so \
    vendor/umi/MAX/proprietary/lib/libperfservice.so:system/lib/libperfservice.so \
    vendor/umi/MAX/proprietary/lib64/libperfservice.so:system/lib64/libperfservice.so \
    vendor/umi/MAX/proprietary/lib/libpq_cust.so:system/lib/libpq_cust.so \
    vendor/umi/MAX/proprietary/lib64/libpq_cust.so:system/lib64/libpq_cust.so \
    vendor/umi/MAX/proprietary/lib64/libpq_cust.so:system/lib64/libpq_cust.so \
    vendor/umi/MAX/proprietary/lib/libPQDCjni.so:system/lib/libPQDCjni.so \
    vendor/umi/MAX/proprietary/lib64/libPQDCjni.so:system/lib64/libPQDCjni.so \
    vendor/umi/MAX/proprietary/lib/libPQjni.so:system/lib/libPQjni.so \
    vendor/umi/MAX/proprietary/lib64/libPQjni.so:system/lib64/libPQjni.so \
    vendor/umi/MAX/proprietary/lib/libpq_prot.so:system/lib/libpq_prot.so \
    vendor/umi/MAX/proprietary/lib64/libpq_prot.so:system/lib64/libpq_prot.so \
    vendor/umi/MAX/proprietary/lib/libpqservice.so:system/lib/libpqservice.so \
    vendor/umi/MAX/proprietary/lib64/libpqservice.so:system/lib64/libpqservice.so \
    vendor/umi/MAX/proprietary/lib/libSonyIMX230PdafLibrary.so:system/lib/libSonyIMX230PdafLibrary.so \
    vendor/umi/MAX/proprietary/lib64/libSonyIMX230PdafLibrary.so:system/lib64/libSonyIMX230PdafLibrary.so \
    vendor/umi/MAX/proprietary/lib/libspeech_enh_lib.so:system/lib/libspeech_enh_lib.so \
    vendor/umi/MAX/proprietary/lib64/libspeech_enh_lib.so:system/lib64/libspeech_enh_lib.so \
    vendor/umi/MAX/proprietary/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/umi/MAX/proprietary/lib64/libstagefrighthw.so:system/lib64/libstagefrighthw.so \
    vendor/umi/MAX/proprietary/lib/libSwJpgCodec.so:system/lib/libSwJpgCodec.so \
    vendor/umi/MAX/proprietary/lib64/libSwJpgCodec.so:system/lib64/libSwJpgCodec.so \
    vendor/umi/MAX/proprietary/lib64/libterservice.so:system/lib64/libterservice.so \
    vendor/umi/MAX/proprietary/lib/libtouchfilter.so:system/lib/libtouchfilter.so \
    vendor/umi/MAX/proprietary/lib64/libtouchfilter.so:system/lib64/libtouchfilter.so \
    vendor/umi/MAX/proprietary/lib/libudf.so:system/lib/libudf.so \
    vendor/umi/MAX/proprietary/lib64/libudf.so:system/lib64/libudf.so \
    vendor/umi/MAX/proprietary/lib/libui.so:system/lib/libui.so \
    vendor/umi/MAX/proprietary/lib64/libui.so:system/lib64/libui.so \
    vendor/umi/MAX/proprietary/lib/libvcodecdrv.so:system/lib/libvcodecdrv.so \
    vendor/umi/MAX/proprietary/lib64/libvcodecdrv.so:system/lib64/libvcodecdrv.so \
    vendor/umi/MAX/proprietary/lib/libvcodec_oal.so:system/lib/libvcodec_oal.so \
    vendor/umi/MAX/proprietary/lib/libvcodec_utility.so:system/lib/libvcodec_utility.so \
    vendor/umi/MAX/proprietary/lib64/libvcodec_utility.so:system/lib64/libvcodec_utility.so \
    vendor/umi/MAX/proprietary/lib64/libwapi.so:system/lib64/libwapi.so \
    vendor/umi/MAX/proprietary/lib64/libwifitest.so:system/lib64/libwifitest.so \
    vendor/umi/MAX/proprietary/lib/drm/libdrmmtkplugin.so:system/lib/drm/libdrmmtkplugin.so \
    vendor/umi/MAX/proprietary/lib/libaudiomtkdcremoval.so:system/lib/libaudiomtkdcremoval.so \
    vendor/umi/MAX/proprietary/lib/libbessurround_mtk.so:system/lib/libbessurround_mtk.so \
    vendor/umi/MAX/proprietary/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
    vendor/umi/MAX/proprietary/lib/libDR.so:system/lib/libDR.so \
    vendor/umi/MAX/proprietary/lib/libfgauge.so:system/lib/libfgauge.so \
    vendor/umi/MAX/proprietary/lib/libfusion.so:system/lib/libfusion.so \
    vendor/umi/MAX/proprietary/lib/libJniAtvService.so:system/lib/libJniAtvService.so \
    vendor/umi/MAX/proprietary/lib/libmemoryDumpEncoder.so:system/lib/libmemoryDumpEncoder.so \
    vendor/umi/MAX/proprietary/lib/libmhalImageCodec.so:system/lib/libmhalImageCodec.so \
    vendor/umi/MAX/proprietary/lib/libmnl.so:system/lib/libmnl.so \
    vendor/umi/MAX/proprietary/lib/libmp4enc_sa.ca7.so:system/lib/libmp4enc_sa.ca7.so \
    vendor/umi/MAX/proprietary/lib/libmpe.driver.so:system/lib/libmpe.driver.so \
    vendor/umi/MAX/proprietary/lib/libmpe.sensorlistener.so:system/lib/libmpe.sensorlistener.so \
    vendor/umi/MAX/proprietary/lib/libm.so:system/lib/libm.so \
    vendor/umi/MAX/proprietary/lib/libmtcloader.so:system/lib/libmtcloader.so \
    vendor/umi/MAX/proprietary/lib/libMtkOmxAdpcmDec.so:system/lib/libMtkOmxAdpcmDec.so \
    vendor/umi/MAX/proprietary/lib/libMtkOmxAdpcmEnc.so:system/lib/libMtkOmxAdpcmEnc.so \
    vendor/umi/MAX/proprietary/lib/libMtkOmxAlacDec.so:system/lib/libMtkOmxAlacDec.so \
    vendor/umi/MAX/proprietary/lib/libMtkOmxApeDec.so:system/lib/libMtkOmxApeDec.so \
    vendor/umi/MAX/proprietary/lib/libMtkOmxCore.so:system/lib/libMtkOmxCore.so \
    vendor/umi/MAX/proprietary/lib/libMtkOmxFlacDec.so:system/lib/libMtkOmxFlacDec.so \
    vendor/umi/MAX/proprietary/lib/libMtkOmxG711Dec.so:system/lib/libMtkOmxG711Dec.so \
    vendor/umi/MAX/proprietary/lib/libMtkOmxGsmDec.so:system/lib/libMtkOmxGsmDec.so \
    vendor/umi/MAX/proprietary/lib/libMtkOmxMp3Dec.so:system/lib/libMtkOmxMp3Dec.so \
    vendor/umi/MAX/proprietary/lib/libMtkOmxRawDec.so:system/lib/libMtkOmxRawDec.so \
    vendor/umi/MAX/proprietary/lib/libMtkOmxVdecEx.so:system/lib/libMtkOmxVdecEx.so \
    vendor/umi/MAX/proprietary/lib/libMtkOmxVenc.so:system/lib/libMtkOmxVenc.so \
    vendor/umi/MAX/proprietary/lib/libMtkOmxVorbisEnc.so:system/lib/libMtkOmxVorbisEnc.so \
    vendor/umi/MAX/proprietary/lib/libpq_cust.so:system/lib/libpq_cust.so \
    vendor/umi/MAX/proprietary/lib/libshowlogo.so:system/lib/libshowlogo.so \
    vendor/umi/MAX/proprietary/lib/libSwJpgCodec.so:system/lib/libSwJpgCodec.so \
    vendor/umi/MAX/proprietary/lib/libthermalalgo.so:system/lib/libthermalalgo.so \
    vendor/umi/MAX/proprietary/lib/libtimestretch.so:system/lib/libtimestretch.so \
    vendor/umi/MAX/proprietary/lib/libvc1dec_sa.ca7.so:system/lib/libvc1dec_sa.ca7.so \
    vendor/umi/MAX/proprietary/lib/libvp8dec_sa.ca7.so:system/lib/libvp8dec_sa.ca7.so \
    vendor/umi/MAX/proprietary/lib/libvp8enc_sa.ca7.so:system/lib/libvp8enc_sa.ca7.so \
    vendor/umi/MAX/proprietary/lib/libvp9dec_sa.ca7.so:system/lib/libvp9dec_sa.ca7.so \
    vendor/umi/MAX/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/umi/MAX/proprietary/vendor/lib64/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib64/mediadrm/libdrmclearkeyplugin.so \
    vendor/umi/MAX/proprietary/vendor/lib/mediadrm/libmockdrmcryptoplugin.so:system/vendor/lib/mediadrm/libmockdrmcryptoplugin.so \
    vendor/umi/MAX/proprietary/vendor/lib64/mediadrm/libmockdrmcryptoplugin.so:system/vendor/lib64/mediadrm/libmockdrmcryptoplugin.so \
    vendor/umi/MAX/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/umi/MAX/proprietary/vendor/lib/libfrsdk.so:system/vendor/lib/libfrsdk.so \
    vendor/umi/MAX/proprietary/vendor/lib64/libfrsdk.so:system/vendor/lib64/libfrsdk.so \
    vendor/umi/MAX/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/umi/MAX/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/umi/MAX/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/umi/MAX/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/umi/MAX/proprietary/xbin/BGW:system/xbin/BGW \
    vendor/umi/MAX/proprietary/xbin/mnld:system/xbin/mnld \
    vendor/umi/MAX/proprietary/xbin/MPED:system/xbin/MPED \
    vendor/umi/MAX/proprietary/lib64/hw/lights.mt6755.so:system/lib64/hw/lights.mt6755.so
